In [3]:
import numpy as np

start = [[1, 2, 3, 4], 
         [9, 5, 6, 7], 
         [10, 11, 8, 0], 
         [13, 14, 15, 12]]

a = np.array(start)

print(a)
print(a[0][0])
print(a[0,0])

[[ 1  2  3  4]
 [ 9  5  6  7]
 [10 11  8  0]
 [13 14 15 12]]
1
1


In [7]:
import time
start = time.time()

end = time.time()
print(end-start)

2.09808349609375e-05


In [139]:
import sys
sys.path.insert(0, "aipython")

import time
import numpy as np
from aipython.searchGeneric import *
from aipython.searchProblem import *
from aipython.cspProblem import *
from aipython.cspSearch import *

grid = [[9, 5, 0, 8, 2, 7, 3, 0, 0],
        [0, 8, 0, 1, 4, 0, 0, 5, 0],
        [0, 1, 0, 5, 9, 0, 0, 0, 0],
        [8, 3, 0, 0, 0, 0, 0, 7, 5],
        [1, 6, 9, 7, 5, 2, 4, 3, 0],
        [0, 7, 0, 0, 8, 0, 0, 6, 0],
        [0, 9, 1, 0, 6, 0, 8, 4, 0],
        [7, 0, 8, 0, 3, 1, 0, 0, 6],
        [6, 2, 0, 4, 7, 8, 0, 9, 0]]
loc = (1,1)

print(loc)
a = np.array(grid)
b = np.where(a == 0)

print('b = ',b)
print()
print(b[0])
print(b[1])
print()
row = list(b[0])
col = list(b[1])
print('0000')
print((row[0],col[0]))
print(a[row[5],col[5]])

domains={}
for i in range(9):
    for j in range(9):
        if a[i][j] == 0:
            arr = {1, 2, 3, 4, 5, 6, 7, 8, 9}
            for m in a[i,...]:
                if m in arr:
                    arr.remove(m)
            for m in a[...,j]:
                if m in arr:
                    arr.remove(m)
            for m in a[(i//3)*3:(i//3+1)*3,(j//3)*3:(j//3+1)*3].flatten():
                if m in arr:
                    arr.remove(m)
            domains[(i, j)] = arr
            
print(domains)    
    



(1, 1)
b =  (array([0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 5, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8]), array([2, 7, 8, 0, 2, 5, 6, 8, 0, 2, 5, 6, 7, 8, 2, 3, 4, 5, 6, 8, 0, 2,
       3, 5, 6, 8, 0, 3, 5, 8, 1, 3, 6, 7, 2, 6, 8]))

[0 0 0 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 4 5 5 5 5 5 5 6 6 6 6 7 7 7 7 8 8 8]
[2 7 8 0 2 5 6 8 0 2 5 6 7 8 2 3 4 5 6 8 0 2 3 5 6 8 0 3 5 8 1 3 6 7 2 6 8]

0000
(0, 2)
0
{(0, 2): {4, 6}, (0, 7): {1}, (0, 8): {1, 4}, (1, 0): {2, 3}, (1, 2): {2, 3, 6, 7}, (1, 5): {3, 6}, (1, 6): {2, 6, 7, 9}, (1, 8): {2, 7, 9}, (2, 0): {2, 3, 4}, (2, 2): {2, 3, 4, 6, 7}, (2, 5): {3, 6}, (2, 6): {2, 6, 7}, (2, 7): {2, 8}, (2, 8): {2, 4, 7, 8}, (3, 2): {2, 4}, (3, 3): {6, 9}, (3, 4): {1}, (3, 5): {4, 6, 9}, (3, 6): {1, 2, 9}, (4, 8): {8}, (5, 0): {2, 4, 5}, (5, 2): {2, 4, 5}, (5, 3): {3, 9}, (5, 5): {3, 4, 9}, (5, 6): {1, 2, 9}, (5, 8): {1, 2, 9}, (6, 0): {3, 5}, (6, 3): {2}, (6, 5): {5}, (6, 8): {2, 3, 7}, (7, 1): {4}, (7, 3): {2, 9}, (7, 6): {2

In [135]:

print(a[1,...])
print(a[...,1])
print(a[(loc[0]//3)*3:(loc[0]//3+1)*3,(loc[1]//3)*3:(loc[1]//3+1)*3].flatten)

[0 8 0 1 4 0 0 5 0]
[5 8 1 3 6 7 9 0 2]
<built-in method flatten of numpy.ndarray object at 0x7fba235d63a0>


In [141]:
for i in range(9):
        for j in range(9):
            for m in range(9):
                if m != i and a[i][j] == 0:
                    constrain.append(Constraint([(i, j), (m, j)],notequal))

NameError: name 'constrain' is not defined

In [145]:
def notequal(a, b):
    return a!=b
a = np.array(grid)
constrain=[]
for i in range(9):
    for j in range(9):
        for m in range(9):
            if m != i and a[i][j] == 0:
                constrain.append(Constraint([(i, j), (m, j)],notequal))
        for m in range(9):
            if m != j:
                constrain.append(Constraint([(i, j), (i, m)],notequal))
        for m in range((i//3)*3,(i//3+1)*3):
            for n in range((j//3)*3,(j//3+1)*3):
                if m != i and n != j:
                    constrain.append(Constraint([(i, j), (m, n)],notequal))
                    
print(constrain)                    

[notequal[(0, 0), (0, 1)], notequal[(0, 0), (0, 2)], notequal[(0, 0), (0, 3)], notequal[(0, 0), (0, 4)], notequal[(0, 0), (0, 5)], notequal[(0, 0), (0, 6)], notequal[(0, 0), (0, 7)], notequal[(0, 0), (0, 8)], notequal[(0, 0), (1, 1)], notequal[(0, 0), (1, 2)], notequal[(0, 0), (2, 1)], notequal[(0, 0), (2, 2)], notequal[(0, 1), (0, 0)], notequal[(0, 1), (0, 2)], notequal[(0, 1), (0, 3)], notequal[(0, 1), (0, 4)], notequal[(0, 1), (0, 5)], notequal[(0, 1), (0, 6)], notequal[(0, 1), (0, 7)], notequal[(0, 1), (0, 8)], notequal[(0, 1), (1, 0)], notequal[(0, 1), (1, 2)], notequal[(0, 1), (2, 0)], notequal[(0, 1), (2, 2)], notequal[(0, 2), (1, 2)], notequal[(0, 2), (2, 2)], notequal[(0, 2), (3, 2)], notequal[(0, 2), (4, 2)], notequal[(0, 2), (5, 2)], notequal[(0, 2), (6, 2)], notequal[(0, 2), (7, 2)], notequal[(0, 2), (8, 2)], notequal[(0, 2), (0, 0)], notequal[(0, 2), (0, 1)], notequal[(0, 2), (0, 3)], notequal[(0, 2), (0, 4)], notequal[(0, 2), (0, 5)], notequal[(0, 2), (0, 6)], notequal[(0